---
# Delete indices in case of some error
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices in case of some error
    options:
      ignore_empty_list: True
      continue_if_exception: False
    filters:
    - filtertype: pattern
      kind: suffix
      value: ${CURRENT_DATETIME}
      exclude:
    - filtertype: pattern
      kind: prefix
      value: ${INDEX_NAME_PREFIX}
      exclude: