# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - ${ELASTICSEARCH_HOST}
  http_auth: ${ELASTICSEARCH_USER_PASSWORD}
  timeout: 30
  
logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']